spring.application.name=peliculas-v7
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/intermodular_peliculas_v2
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jackson.property-naming-strategy=SNAKE_CASE
server.error.whitelabel.enabled=false